export const ITEMS = [
  { id: 1, name: "Maggi Masala", price: 20 },
  { id: 2, name: "Maggi Veggie Pack", price: 25 },
  { id: 3, name: "Maggi Chicken Pack", price: 30 },
  { id: 4, name: "Maggi Sauce", price: 10 },
  { id: 5, name: "Instant Oats", price: 40 },
  { id: 6, name: "Bread Loaf", price: 25 },
  { id: 7, name: "Peanut Butter", price: 60 },
  { id: 8, name: "Jam", price: 35 },
  { id: 9, name: "Milk Powder", price: 120 },
  { id: 10, name: "Tea Bags (10 pcs)", price: 30 },
  { id: 11, name: "Coffee Powder", price: 80 },
  { id: 12, name: "Sugar (1kg)", price: 50 },
  { id: 13, name: "Salt (500g)", price: 20 },
  { id: 14, name: "Rice (1kg)", price: 60 },
  { id: 15, name: "Wheat Flour (1kg)", price: 50 },
  { id: 16, name: "Pasta (500g)", price: 40 },
  { id: 17, name: "Noodles (500g)", price: 30 },
  { id: 18, name: "Corn Flakes", price: 80 },
  { id: 19, name: "Biscuits Pack", price: 20 },
  { id: 20, name: "Cookies Pack", price: 35 },
  { id: 21, name: "Chocolates", price: 25 },
  { id: 22, name: "Instant Soup Pack", price: 20 },
  { id: 23, name: "Tomato Ketchup", price: 40 },
  { id: 24, name: "Chili Sauce", price: 35 },
  { id: 25, name: "Pepsi (500ml)", price: 30 },
  { id: 26, name: "Coke (500ml)", price: 30 },
  { id: 27, name: "Juice Pack", price: 25 },
  { id: 28, name: "Mineral Water (1L)", price: 15 },
  { id: 29, name: "Energy Drink", price: 50 },
  { id: 30, name: "Instant Upma Mix", price: 25 },
  { id: 31, name: "Instant Idli Mix", price: 30 },
  { id: 32, name: "Dosa Batter Pack", price: 40 },
  { id: 33, name: "Paneer (200g)", price: 80 },
  { id: 34, name: "Eggs (6 pcs)", price: 60 },
  { id: 35, name: "Cheese Slice Pack", price: 50 },
  { id: 36, name: "Butter (100g)", price: 40 },
  { id: 37, name: "Olive Oil (100ml)", price: 100 },
  { id: 38, name: "Vegetable Oil (1L)", price: 120 },
  { id: 39, name: "Chana Dal (500g)", price: 60 },
  { id: 40, name: "Moong Dal (500g)", price: 70 },
  { id: 41, name: "Toor Dal (500g)", price: 80 },
  { id: 42, name: "Soya Chunks", price: 60 },
  { id: 43, name: "Dry Fruits Pack", price: 150 },
  { id: 44, name: "Cashews (100g)", price: 100 },
  { id: 45, name: "Almonds (100g)", price: 120 },
  { id: 46, name: "Raisins (100g)", price: 80 },
  { id: 47, name: "Masala Powder (50g)", price: 25 },
  { id: 48, name: "Turmeric Powder", price: 20 },
  { id: 49, name: "Coriander Powder", price: 25 },
  { id: 50, name: "Chili Powder", price: 20 },
  { id: 51, name: "Garlic Paste", price: 35 },
  { id: 52, name: "Ginger Paste", price: 35 },
  { id: 53, name: "Green Chutney Pack", price: 30 },
  { id: 54, name: "Red Chutney Pack", price: 30 },
  { id: 55, name: "Curd (200ml)", price: 25 },
  { id: 56, name: "Yogurt Pack", price: 50 },
  { id: 57, name: "Instant Coffee Sachets", price: 40 },
  { id: 58, name: "Green Tea Sachets", price: 35 },
  { id: 59, name: "Oreo Pack", price: 25 },
  { id: 60, name: "Muffins", price: 30 },
  { id: 61, name: "Cupcakes", price: 35 },
  { id: 62, name: "Chips Pack", price: 20 },
  { id: 63, name: "Nuts Mix Pack", price: 50 },
  { id: 64, name: "Samosa (2 pcs)", price: 25 },
  { id: 65, name: "Paneer Sandwich", price: 50 },
  { id: 66, name: "Veg Sandwich", price: 35 },
  { id: 67, name: "Chicken Sandwich", price: 60 },
  { id: 68, name: "Fruit Jam Pack", price: 30 },
  { id: 69, name: "Honey Bottle", price: 70 },
  { id: 70, name: "Maple Syrup", price: 90 },
  { id: 71, name: "Instant Rava Upma", price: 25 },
  { id: 72, name: "Cornflakes with Milk", price: 50 },
  { id: 73, name: "Milk (1L)", price: 50 },
  { id: 74, name: "Chocolate Milk", price: 40 },
  { id: 75, name: "Protein Bar", price: 60 },
  { id: 76, name: "Energy Bar", price: 50 },
  { id: 77, name: "Nuts & Seeds Mix", price: 70 },
  { id: 78, name: "Vegetable Soup", price: 40 },
  { id: 79, name: "Chicken Soup", price: 50 },
  { id: 80, name: "Maggi Bowl Pack", price: 30 },
  { id: 81, name: "Peanut Chikki", price: 25 },
  { id: 82, name: "Gujia Pack", price: 35 },
  { id: 83, name: "Instant Dhokla Mix", price: 30 },
  { id: 84, name: "Idli Batter Sachet", price: 35 },
  { id: 85, name: "Dosa Batter Sachet", price: 35 },
  { id: 86, name: "Vermicelli (Seviyan)", price: 40 },
  { id: 87, name: "Instant Kheer Mix", price: 45 },
  { id: 88, name: "Chikki Bar", price: 20 },
  { id: 89, name: "Dry Fruit Ladoo", price: 50 },
  { id: 90, name: "Puffed Rice", price: 20 },
  { id: 91, name: "Corn Flakes Snack", price: 25 },
  { id: 92, name: "Instant Pizza Pack", price: 60 },
  { id: 93, name: "Veg Burger Patty", price: 50 },
  { id: 94, name: "Chicken Burger Patty", price: 70 },
  { id: 95, name: "Cheese Spread", price: 40 },
  { id: 96, name: "Jam Sandwich", price: 30 },
  { id: 97, name: "Chocolate Spread", price: 50 },
  { id: 98, name: "Fruit Snacks", price: 30 },
  { id: 99, name: "Instant Pancake Mix", price: 45 },
  { id: 100, name: "Maple Pancake Syrup", price: 80 },
];
